# Generated by Django 4.0.6 on 2023-01-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(default=1, max_length=1000),
        ),
    ]
